# Generated by Django 3.1.2 on 2020-12-08 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySyllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='', max_length=20)),
                ('assignmentWeight', models.CharField(max_length=20)),
                ('gradeScale', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('officeHours', models.CharField(max_length=20)),
                ('officeNumber', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitHubTest.mysyllabus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitHubTest.myuser')),
            ],
        ),
    ]
