# Generated by Django 3.1.3 on 2020-12-13 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MySyllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=10)),
                ('courseDescription', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitHubTest.mycourse')),
            ],
        ),
        migrations.CreateModel(
            name='MyUserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('lastName', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('officeHours', models.CharField(max_length=20)),
                ('officeNumber', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitHubTest.myuserlogin')),
            ],
        ),
        migrations.CreateModel(
            name='MySyllabusComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitHubTest.mysyllabus')),
            ],
        ),
        migrations.AddField(
            model_name='mysyllabus',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitHubTest.myuser'),
        ),
        migrations.CreateModel(
            name='MySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionNumber', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitHubTest.mycourse')),
                ('teachingAssistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitHubTest.myuser')),
            ],
        ),
        migrations.AddField(
            model_name='mycourse',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GitHubTest.myuser'),
        ),
    ]
