# Generated by Django 3.1.2 on 2020-11-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitHubTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
