# Generated by Django 3.1.3 on 2020-12-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitHubTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysyllabus',
            name='courseName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
