# Generated by Django 3.1.3 on 2020-12-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitHubTest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysection',
            old_name='teaching_assistant',
            new_name='teachingAssistant',
        ),
        migrations.AddField(
            model_name='mysection',
            name='sectionNumber',
            field=models.IntegerField(default=0),
        ),
    ]
