# Generated by Django 3.1.2 on 2020-11-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GitHubTest', '0002_adin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adin',
            new_name='Admins',
        ),
    ]
