# Generated by Django 3.1.2 on 2020-12-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GitHubTest', '0003_auto_20201130_0106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admins',
        ),
    ]
